Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,7 +73,7 @@ jobs:
             sudo apt install -qq libx11-dev libx11-xcb-dev desktop-file-utils appstream-util
           elif [ "$RUNNER_OS" == "Windows" ]; then
             choco install -y --force openssl.light --version=1.1.1
-            echo "C:\\Program Files\\OpenSSL" >> $GITHUB_PATH
+            echo "C:\Program Files\OpenSSL" >> $GITHUB_PATH
           else
             echo "$RUNNER_OS not supported"
             exit 1
@@ -312,8 +312,7 @@ jobs:
       - name: Verify that the app metadata contains the release
         shell: bash
         run: |
-          grep "version=\"${{ steps.deploy_check.outputs.version }}\"" src/res/com.ulduzsoft.Birdtray.appdata.xml -q || (echo "Version not found in src/res/com.ulduzsoft.Birdtray.appdata.xml"; exit 1)
-
+          grep "version=\"${{ steps.deploy_check.outputs.version }}\"" src/res/com.ulduzsoft.Birdtray.appdata.xml -q || (echo "Version not found in src/res/com.ulduzsoft.Birdtray.appdata.xml"; ex[...]
       - name: Download installer (x64)
         uses: actions/download-artifact@v4
         with:
